name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Testing
        run: |
          ls
          pwd
          cat main.py
          cat Dockerfile
          cat requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: elixir384
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t elixir384/devops_lab_500109921:v1.0.1 .
          docker push elixir384/devops_lab_500109921:v1.0.1